### ISSUE TITLE
Version 1.5 Issues

### ISSUE THREAD

**Issue by war59312** [Xeroday/Spotify-Ad-Blocker#38]
1.) Unable to connect to ad servers over and over again.
2.) Please stop telling me it's hidden on every minimize, once is enough.
3.) Please have a real about screen with at least version number and date.
4.) Copyright of exe is 2014.

**Comment by war59312** [comment]
Wow, ok another version now. 

First song I played it was muted. :(

Redeemed by Big Daddy Weave

Sussfully blocked next 2 ads.

Then muted next song, Not Alone by Red.

In fact it is blocking every song. :(

**Comment by war59312** [comment]
Log has this:

```
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:4380
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Int32 timeout, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at EZBlocker.WebHelperHook.GetPage(String URL)
   at EZBlocker.WebHelperHook.GetStatus()
   at EZBlocker.Main.MainTimer_Tick(Object sender, EventArgs e)
```

So usless version as every song is being muted.

**Comment by Xeroday** [comment]
Use EZBlocker v1.4 for Spotify 0.9.X

**Comment by war59312** [comment]
Got ya, thanks. Yeah should say 1.0+ is requried for Ezblocker 1.5.

Also, perhaps add a simple check. Simply read version info of %userprofile%\AppData\Roaming\Spotify\Spotify.exe and if less than 1.0.1 then tell the user to upgrade and send to download page.

By the way, quicker mirror @ https://userscloud.com/nb7vszmai5bx

**Comment by Xeroday** [comment]
Added Spotify version checking for 1.5.1.1.
